version: '3.1'

services:
  mysqldb:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: musiccatalog
      MYSQL_ROOT_PASSWORD: password

  musiccatalog:
    image: musiccatalog
    depends_on:
      - demo-mysql
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysqldb:3306/musiccatalog'
      SPRING_PROFILES_ACTIVE: 'mysql'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3